/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "deouvzsxhkhzikrjczxc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlb3V2enN4aGtoemlrcmpjenhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMjE1ODAsImV4cCI6MjA3Njc5NzU4MH0.Y6Z1KS-37Pmkaa-U13IRu_SctqS9ZG21B_0KUFZP3uk"